#!/bin/sh
#copy this script to .git/hooks and change the second path to the directory of your vrep application
#it links the finken lua scripts in this repository so vrep can find them
#on OS X, the path should be correct for default installations
#does not work for Windows!

ln -sf finken.lua /Applications/vrep/vrep.app/Contents/MacOS/finken.lua
ln -sf finkenPid.lua /Applications/vrep/vrep.app/Contents/MacOS/finkenPid.lua
ln -sf finkenCore.lua /Applications/vrep/vrep.app/Contents/MacOS/finkenCore.lua
ln -sf finkenMeta.lua /Applications/vrep/vrep.app/Contents/MacOS/finkenMeta.lua

