#!/bin/sh
#to execute this script type ./linkScrips into the command line and drag the folder of your VREP installtion into the window
#if you use OS X drag the vrep.app into the Terminal window
#it links the finken lua scripts in this repository to the main vrep folder so vrep can find them
#does not work for Windows!

if [[ "$OSTYPE" = darwin* ]]; then 
	ln -sf "$PWD/finken.lua" "$1/Contents/MacOS/finken.lua";
	ln -sf "$PWD/finkenPid.lua" "$1/Contents/MacOS/finkenPid.lua";
	ln -sf "$PWD/finkenCore.lua" "$1/Contents/MacOS/finkenCore.lua";
	ln -sf "$PWD/finkenMeta.lua" "$1/Contents/MacOS/finkenMeta.lua";
	echo "Your machine runs OS X. Scripts were linked to $1/Contents/MacOS"
else
	ln -sf "$PWD/finken.lua" $1;
	ln -sf "$PWD/finkenPid.lua" $1;
	ln -sf "$PWD/finkenCore.lua" $1;
	ln -sf "$PWD/finkenMeta.lua" $1;
	echo "your scripts were linked to $1"
fi	
