#!/bin/sh
#copy this script to .git/hooks and change the second path to the directory of your vrep application
#it links the finken lua scripts in this repository so vrep can find them
#on OS X, the path should be correct for default installations
#does not work for Windows!

ln -sf $GIT_DIR/../vrep/scripts/finken.lua /home/dom/Software/vrep/finken.lua
ln -sf $GIT_DIR/../vrep/scripts/finkenPid.lua /home/dom/Software/vrep/finkenPid.lua
ln -sf $GIT_DIR/../vrep/scripts/finkenCore.lua /home/dom/Software/vrep/finkenCore.lua
ln -sf $GIT_DIR/../vrep/scripts/finkenMeta.lua /home/dom/Software/vrep/finkenMeta.lua

