#!/bin/sh
#copy this script to .git/hooks and change the second path to the directory of your vrep application
#it links the finken lua scripts in this repository so vrep can find them
#on OS X, the path should be correct for default installations
#does not work for Windows!

if [[ "$OSTYPE" = darwin* ]]; then 
	ln -sf "$PWD/finken.lua" /Applications/vrep/vrep.app/Contents/MacOS/finken.lua;
	ln -sf "$PWD/finkenPid.lua" /Applications/vrep/vrep.app/Contents/MacOS/finkenPid.lua;
	ln -sf "$PWD/finkenCore.lua" /Applications/vrep/vrep.app/Contents/MacOS/finkenCore.lua;
	ln -sf "$PWD/finkenMeta.lua" /Applications/vrep/vrep.app/Contents/MacOS/finkenMeta.lua;
	echo "Your machine runs OS X. Scripts were linked to /Applications/vrep/vrep.app/Contents/MacOS"
else
	ln -sf "$PWD/finken.lua" $1;
	ln -sf "$PWD/finkenPid.lua" $1;
	ln -sf "$PWD/finkenCore.lua" $1;
	ln -sf "$PWD/finkenMeta.lua" $1;
	echo "your scripts were linked to $1"
fi	
